### To create a pet, you must first log in, this request will return an access token and a refresh token that you will need to use in the other requests [Admin user]

POST localhost:7777/api/auth/login
Content-Type: application/json

{
"username": "adminUser2",
"password": "securePassword"
}

### Create pet. This pet is already in the database, you must update the values

POST localhost:7777/api/pets
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJyc2Eta2V5IiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWRtaW5Vc2VyMiIsImV4cCI6MTczNTU5NTc1MCwiaWF0IjoxNzM1NTkyMTUwLCJyb2xlcyI6WyJBRE1JTiJdfQ.2hbgsbGqJJYrI8zNKfeYFkvyqFvJ4--y2ZIy9Ka4RMzxA9HyUCoIifhjMLMhUNTxiNNNKj86zB-gqNauG2RF5gH5IWrclygw9ok4qn8gSNbcGwwMAWy2CoirkhDPbNENiWRLZamXGHWNQjxM3SgjC1RV4_4MkvNtExumzcy_A7VhqhxhnUX_tkG0ul1jxgz4z9OGwS1yNlIs_U0cv-P3TtuGp-mejVk5WyzRCF6qOUb1niSyYMmk6WoPCOVNcmMxIXbETqlrajTBrQsi9VIbxPCwLjaE3Jpd51QLVhH8PXNRQSafGkiY4K47El-LXcrPAmSa3AI-k7DJiMfkbxcT9Q

{
"name": "Billy",
"age": 6,
"typeOfPet": {
"id": 1
},
"location": "Madrid"
}


### View created pets

GET localhost:7777/api/pets
Authorization: Bearer eyJraWQiOiJyc2Eta2V5IiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWRtaW5Vc2VyMiIsImV4cCI6MTczNTY2ODc0MSwiaWF0IjoxNzM1NjY1MTQxLCJyb2xlcyI6WyJBRE1JTiJdfQ.Id0ZIsZ1CdNa0Z50u31zyLG2QGup4x6FJPBDUmmYx-R7-FZijARNIXget14qlQBJSSae8oqxAbTDWTKKlbaErH7WdOivXVMRxih8Gyarw1aNPpzD-lqgtzvwaZuGRwmv1NIlGKhE6QLg6rY535TSunh_LdhqR4FUayPtEnV9w-zV2mygQbdZJA2cQcbrxFSjzlGujlvw52ek9jqUqc6WxaTGCtVYfS8NMfQNtE8yKVQk3Quyzq3DPeLRTe4_m27ETi2DPf0mFb8zStNWLHiAOzF3eWtQFlmUPXG8x9J1H7Mdm0rKkonxKrSn3EIoX0e9FtMfeGM1QNj_WGVUlwggyg


